### ISSUE TITLE
Feature: Product > Criar produto (admin)

### ISSUE THREAD

**Issue by GlasiCR** [arnia-linkcom-gamification/Backend-Culture-Code#23]

**Comment by orionalves** [comment]
Acho que faltou a task de criar a entidade produto.

**Comment by orionalves** [comment]
Cria a task de criar a entidade produto e finaliza ela antes de finalizar criar a rota produto.

**Comment by GlasiCR** [comment]
Sim, faltou...na hora vi. Criei a task, mas já criei a entidade tbm rsrs
